// ROOMS
export const GET_ROOMS = "GET_ROOMS";
export const CREATE_ROOM = "CREATE_ROOM";
export const EXISTS_ROOM = "CREATE_ROOM";
export const SET_CURRENT_ROOM = "SET_CURRENT_ROOM";

// PEOPLE
export const GET_PEOPLE = "GET_PEOPLE";
export const REMOVE_PEOPLE = "REMOVE_PEOPLE";
export const GET_HOST = "GET_HOST";
export const UPDATE_MY_STATUS = "UPDATE_MY_STATUS";
export const GET_MY_ID = "GET_MY_ID";

// GAME
export const RESET_GAME = "RESET_GAME";
export const START_GAME = "START_GAME";
export const GET_GAME_PROPERTY_SETS = "GET_GAME_PROPERTY_SETS";
export const GET_PLAYER_HANDS = "GET_PLAYER_HANDS";
export const GET_PLAYER_BANKS = "GET_PLAYER_BANKS";
export const GET_PLAYER_COLLECTIONS = "GET_PLAYER_COLLECTIONS";
export const GET_COLLECTIONS = "GET_COLLECTIONS";
export const REMOVE_COLLECTIONS = "REMOVE_COLLECTIONS";
export const GET_GAME_CARDS = "GET_GAME_CARDS";
export const GAME_STATUS = "GAME_STATUS";
export const GET_PLAYER_REQUESTS = "GET_PLAYER_REQUESTS";
export const REMOVE_ALL_PLAYER_REQUESTS = "REMOVE_ALL_PLAYER_REQUESTS";
export const GET_REQUESTS = "GET_REQUESTS";
export const REMOVE_ALL_REQUESTS = "REMOVE_ALL_REQUESTS";

export const GET_DRAW_PILE = "GET_DRAW_PILE";
export const GET_ACTIVE_PILE = "GET_ACTIVE_PILE";
export const GET_DISCARD_PILE = "GET_DISCARD_PILE";
export const GET_PLAYER_TURN = "GET_PLAYER_TURN";

export const GET_PLAYERS = "GET_PLAYERS";
export const UPDATE_MY_NAME = "UPDATE_MY_NAME";

export const DRAW_TURN_STARTING_CARDS = "DRAW_TURN_STARTING_CARDS";
export const DISCARD_CARDS = "DISCARD_CARDS";

export const UPDATE_DISPLAY_MODE = "UPDATE_DISPLAY_MODE";

// Card selection
export const CARD_SET_SELECTION_ENABLE = "CARD_SET_SELECTION_ENABLE";
export const CARD_SET_SELECTION_TYPE = "CARD_SET_SELECTION_TYPE";
export const CARD_SET_SELECTION_LIMIT = "CARD_SET_SELECTION_LIMIT";
export const CARD_SET_SELECTABLE = "CARD_SET_SELECTABLE";
export const CARD_ADD_SELECTABLE_VALUE = "CARD_ADD_SELECTABLE_VALUE";
export const CARD_REMOVE_SELECTABLE_VALUE = "CARD_REMOVE_SELECTABLE_VALUE";
export const CARD_TOGGLE_SELECTABLE_VALUE = "CARD_TOGGLE_SELECTABLE_VALUE";
export const CARD_SET_SELECTED = "CARD_SET_SELECTED";
export const CARD_ADD_SELECTED_VALUE = "CARD_ADD_SELECTED_VALUE";
export const CARD_REMOVE_SELECTED_VALUE = "CARD_REMOVE_SELECTED_VALUE";
export const CARD_TOGGLE_SELECTED_VALUE = "CARD_TOGGLE_SELECTED_VALUE";

export const COLLECTION_SET_SELECTION_ENABLE = "COLLECTION_SET_SELECTION_ENABLE";
export const COLLECTION_SET_SELECTION_TYPE = "COLLECTION_SET_SELECTION_TYPE";
export const COLLECTION_SET_SELECTION_LIMIT = "COLLECTION_SET_SELECTION_LIMIT";
export const COLLECTION_SET_SELECTABLE = "COLLECTION_SET_SELECTABLE";
export const COLLECTION_ADD_SELECTABLE_VALUE = "COLLECTION_ADD_SELECTABLE_VALUE";
export const COLLECTION_REMOVE_SELECTABLE_VALUE = "COLLECTION_REMOVE_SELECTABLE_VALUE";
export const COLLECTION_TOGGLE_SELECTABLE_VALUE = "COLLECTION_TOGGLE_SELECTABLE_VALUE";
export const COLLECTION_SET_SELECTED = "COLLECTION_SET_SELECTED";
export const COLLECTION_ADD_SELECTED_VALUE = "COLLECTION_ADD_SELECTED_VALUE";
export const COLLECTION_REMOVE_SELECTED_VALUE = "COLLECTION_REMOVE_SELECTED_VALUE";
export const COLLECTION_TOGGLE_SELECTED_VALUE = "COLLECTION_TOGGLE_SELECTED_VALUE";

export const PERSON_SET_SELECTION_ENABLE = "PERSON_SET_SELECTION_ENABLE";
export const PERSON_SET_SELECTION_TYPE = "PERSON_SET_SELECTION_TYPE";
export const PERSON_SET_SELECTION_LIMIT = "PERSON_SET_SELECTION_LIMIT";
export const PERSON_SET_SELECTABLE = "PERSON_SET_SELECTABLE";
export const PERSON_ADD_SELECTABLE_VALUE = "PERSON_ADD_SELECTABLE_VALUE";
export const PERSON_REMOVE_SELECTABLE_VALUE = "PERSON_REMOVE_SELECTABLE_VALUE";
export const PERSON_TOGGLE_SELECTABLE_VALUE = "PERSON_TOGGLE_SELECTABLE_VALUE";
export const PERSON_SET_SELECTED = "PERSON_SET_SELECTED";
export const PERSON_ADD_SELECTED_VALUE = "PERSON_ADD_SELECTED_VALUE";
export const PERSON_REMOVE_SELECTED_VALUE = "PERSON_REMOVE_SELECTED_VALUE";
export const PERSON_TOGGLE_SELECTED_VALUE = "PERSON_TOGGLE_SELECTED_VALUE";
